# Generated by Django 3.0.3 on 2020-05-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IBPricesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=7)),
                ('date', models.DateTimeField()),
                ('last', models.DecimalField(decimal_places=6, max_digits=11)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
